# Generated by Django 6.0.6 on 2026-06-24 14:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp',
            field=models.CharField(default=accounts.models._generate_otp, max_length=6),
        ),
    ]
