# Generated by Django 6.0.6 on 2026-06-24 14:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp',
            field=models.CharField(default=accounts.models._generate_otp, max_length=6),
        ),
    ]
